name: Deploy Pages + Lighthouse Report (static)

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node (para LHCI)
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Preparar carpeta de publicación (site/)
        run: |
          mkdir -p site
          # Copia todo el sitio al staging dir, excluyendo cosas no publicables
          rsync -av --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='.lighthouseci' \
            --exclude='report' \
            ./ site/

      - name: Servir sitio con Python (background)
        run: |
          python3 -m http.server 8000 --bind 127.0.0.1 --directory site &
          sleep 2

      - name: Generar Lighthouse Report en /report/
        run: |
          mkdir -p site/report
          # Target filesystem: escribe reportes en disco (sin servidor LHCI)
          # outputDir + reportFilenamePattern son opciones del target filesystem. :contentReference[oaicite:1]{index=1}
          npx --yes @lhci/cli autorun \
            --collect.url=http://127.0.0.1:8000/ \
            --collect.numberOfRuns=1 \
            --upload.target=filesystem \
            --upload.outputDir=./site/report \
            --upload.reportFilenamePattern=index.%%EXTENSION%%

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build_report
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
